# %%
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
from analysis import Analyzer 
# %%
data = pd.read_csv("cleaned_data.csv", index_col=0)
# %%
# to make the visualizations easier to implement we'll use a class 'Visualizer' that inherits the functions of
# the 'Analyzer' class. This helps keep our code clean and makes it more efficient => no need to write the functions again.
# %%
class Visualizer(Analyzer):
    """Visualizer creates visualizations of the analyzed data through the 'Analyzer' class.
    It includes methods for plotting distributions, generating heatmaps and
    creating scatterplots.
    
    
    Attributes
    ----------
    data: pandas.DataFrame
        The Titanic dataset that is going to be analyzed.
    
    """


    def __init__(self, data):
        """Initializes the class instance with the given (Titanic) dataset.
        
        
        Parameters
        ----------
        data: pandas.DataFrame
            The Titanic dataset that is going to be analyzed. 
            
        """
        super().__init__(data)



    def distribution_numerical(self, column : str):
        """Plots the distribution of observations for a numerical variable
        using a histogram and a kde curve.
        
        
        Parameters
        ----------
        column: str
            The name of the column to analyze. This should be a name of one
            of the columns in the Titanic dataset and must represent
            a numerical variable. 
        
        
        Notes
        -----
        Although this method can technically be used with categorical variables,
        it is designed for numerical variables. 
        
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.distribution_numerical(column = "age")
       
        visualizer.distribution_numerical(column = "fare")
        
        This will generate histograms that show the distribution of the numerical
        variables 'age' and 'fare' with an overlaid kde curve.
        
        """
        plt.figure(figsize = (8,5))
        sns.histplot(self.data[column], kde = True, color = "blue")
        plt.title(f"Distribution of {column}")
        plt.xlabel(column)
        plt.ylabel("frequency")
        plt.show()
        
    
    
    def plot_survival_rate(self, group_by_column : str):
        """Plots survival rates grouped by a categorical variable as a barplot.
        
        
        Parameters
        ----------
        group_by_column: str
            The name of the column used to group survival rates.
            This should be a categorical variable.
            
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.plot_survival_rate("who")
        
        visualizer.plot_survival_rate("pclass") 
        
        This will generate barplots of the survival rates grouped by the 
        specific categorical variable ('who', 'pclass').
        
        """
        survival_rates = self.survival_rate(group_by_column)
        plt.figure(figsize = (8,5))
        survival_rates.sort_values().plot(kind = "bar", color = "darkgrey", alpha = 0.7)
        plt.title(f"Survival rates grouped by {group_by_column}")
        plt.xlabel(group_by_column)
        plt.ylabel("Survival Rate")
        plt.xticks(rotation = 360)
        plt.ylim((0,1))
        plt.show()


    
    def ccf_mean_heatmap(self):
        """Creates a heatmap to visualize the average ticket price by
        embarkation town and passenger class.
        
        
        Notes
        -----
        This method uses the pivot table generated by the method 
        'ccf_categorization_mean' from the Analyzer class. 
        
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.ccf_mean_heatmap()
        
        This will generate a heatmap which contains
        - the three embarkation towns as rows (Cherbourg, Queenstown, Southampton)
        - the three passenger classes as columns (1st, 2nd, 3rd)
        - the average ticket price by embarkation town and passenger class as values
        
        """
        pivot_table_mean = self.ccf_categorization_mean()
        
        # Create a heatmap for average fare
        plt.figure(figsize=(8, 6))
        sns.heatmap(pivot_table_mean, annot=True, fmt=".2f", cmap="coolwarm")
        plt.title("Average Fare by Embark Town and Passenger Class")
        plt.xlabel("Passenger Class")
        plt.ylabel("Embark Town")
        plt.show()
    
    
    
    def ccf_count_heatmap(self):
        """Creates a heatmap to visualize the passenger count by 
        embarkation town and passenger class. 
        
        
        Notes
        -----
        This method uses the pivot table generated by the method
        'ccf_categorization_count' from the Analyzer class.
        
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.ccf_count_heatmap()
        
        This will generate a heatmap which contains
        - the three embarkation towns as rows (Cherbourg, Queenstown, Southampton)
        - the three passenger classes as columns (1st, 2nd, 3rd)
        - the passenger count by embarkation town and passenger class as values
        
        """
        pivot_table_count = self.ccf_categorization_count()

        plt.figure(figsize = (8,6))
        sns.heatmap(pivot_table_count, annot=True, fmt=".2f", cmap="coolwarm")
        plt.title("Passenger Count by Embark Town and Passenger Class")
        plt.xlabel("Passenger Class")
        plt.ylabel("Embark Town")
        plt.show()
        
        
    def plot_contingency_heatmap(self, column1: str, column2: str):
        """Creates a heatmap to visualize the contingency table between
        two categorical variables.
        
        
        Parameters
        ----------
        column1: str
            The name of the first column to analyze. 
            This should be a categorical variable.
        column2: str
            The name of the second column to analyze.
            This should also be a categorical variable.
            
            
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.plot_contingency_heatmap("survived", "pclass")
        
        This will generate a heatmap which includes 
        - the survival status as rows (0 and 1 for not survived and survived)
        - the three passenger classes (1st, 2nd, 3rd)
        - the frequencies for each combination of 'survived' and 'pclass' as values
        
        """
        contingency_table = pd.crosstab(self.data[column1], self.data[column2])
        plt.figure(figsize=(8, 6))
        sns.heatmap(contingency_table, annot=True, cmap="coolwarm", fmt="d")
        plt.title(f'Contingency Table: {column1} vs {column2}')
        plt.xlabel(column2)
        plt.ylabel(column1)
        plt.show()



    def basic_scatterplot(self, column1: str, column2: str):
        """Creates a scatterplot to visualize the relationship 
        between two numerical variables.
        
        
        Parameters
        ----------
        column1: str
            The name of the column that is used for the x-axis. 
            This should be a numerical variable.
        column2: str
            The name of the column that is used for the y-axis.
            This should also be a numerical variable.
            
        
        Notes
        -----
        The y-axis is set to a logarithmic scale.
        alpha = 0.5 is used for better visibility of the scatter points
        
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.basic_scatterplot("age", "fare")
        
        This will generate a scatterplot and visualize how age relates to 
        the ticket price.
        
        """
        plt.figure(figsize=(10, 6))
        sns.regplot(x = column1, y = column2, data=data, scatter_kws={'alpha': 0.5})
        plt.yscale('log')  # <-- This makes the y-axis logarithmic

        fare_ticks = [1, 5, 10, 20, 50, 100, 200, 500]  # example values
        plt.yticks(fare_ticks, fare_ticks)
        plt.title(f"Scatterplot of {column1} vs {column2}")
        plt.xlabel(column1)
        plt.ylabel(column2)
        plt.show()
    
    def scatterplot_sorted_by(self, column1: str, column2: str, hue: str):
        """Creates a scatterplot to visualize the relationship between two
        numerical variables grouped by categorical variable.
        
        Parameters
        ----------
        column1: str
            The name of the column that is used for the x-axis. 
            This should be a numerical variable.
        column2: str
            The name of the column that is used for the y-axis.
            This should also be a numerical variable.
        hue: str
            The name of the column representing the groups.
            This should be a categorical variable.
            
        
        Notes
        -----
        The y-axis is set to a logarithmic scale.
        
        
        Examples
        --------
        visualizer = Visualizer(data)
        
        visualizer.scatterplot_sorted_by("age","fare", hue="pclass")
        
        This will generate a scatterplot and visualize how age relates to 
        the ticket price grouped by the ticket price.
        
        """
        sns.lmplot(x = column1, y = column2, data=data, hue = hue, aspect=1.5, scatter_kws={'alpha': 0.5})
        plt.yscale('log')  # <-- This makes the y-axis logarithmic

        fare_ticks = [1, 5, 10, 20, 50, 100, 200, 500]  # example values
        plt.yticks(fare_ticks, fare_ticks)
        plt.title(f"Scatterplot of {column1} vs {column2} by {hue}")
        plt.xlabel(column1)
        plt.ylabel(column2)
        plt.show()

    
# %%
visualizer = Visualizer(data)
# %%
# use the distribution_numerical method to plot the distribution of a
# numerical variable (e.g. age, fare)
visualizer.distribution_numerical(column = "age")
visualizer.distribution_numerical(column = "fare")

# %%
# use the plot_survival_rate method to plot the survival rates (barplot) grouped by a 
# categorical variable (e.g. who, pclass, sex)
visualizer.plot_survival_rate("who")
visualizer.plot_survival_rate("sex")
visualizer.plot_survival_rate("pclass") 
   
# %%
# plot gives us a heatmap which showcases the average price of the different classes in different towns
visualizer.ccf_mean_heatmap()
# %%
visualizer.ccf_count_heatmap()
# %%
# visualizes the correlation between two categorical variables using a heatmap
visualizer.plot_contingency_heatmap("survived", "pclass")
# %%
visualizer.basic_scatterplot("age", "fare")
# %%
visualizer.scatterplot_sorted_by("age","fare", hue="pclass")
